"""Star names for map flavour: the IAU's catalogue of officially named stars.

Pure core, no I/O: generated from ``tools/iau-star-names.csv`` by
``tools/gen_starnames.py`` — edit the CSV and regenerate rather than hand-editing
this file. Names are cosmetic; systems stay keyed by integer id everywhere.
"""

from __future__ import annotations

import random

NAMES: tuple[str, ...] = (
    'Absolutno',
    'Acamar',
    'Achernar',
    'Achird',
    'Acrab',
    'Acrux',
    'Acubens',
    'Adhafera',
    'Adhara',
    'Adhil',
    'Aerostaticus',
    'Ain',
    'Ainalrami',
    'Aiolos',
    'Aladfar',
    'Alasia',
    'Alaybasan',
    'Albaldah',
    'Albali',
    'Albireo',
    'Alchiba',
    'Alcor',
    'Alcyone',
    'Aldebaran',
    'Alderamin',
    'Aldhanab',
    'Aldhibah',
    'Aldulfin',
    'Alfarasalkamil',
    'Alfirk',
    'Algedi',
    'Algenib',
    'Algieba',
    'Algol',
    'Algorab',
    'Alhena',
    'Alioth',
    'Aljanah',
    'Alkaid',
    'Alkalurops',
    'Alkaphrah',
    'Alkarab',
    'Alkes',
    'Almaaz',
    'Almach',
    'Almighzal',
    'Alnair',
    'Alnasl',
    'Alnilam',
    'Alnitak',
    'Alniyat',
    'Alphard',
    'Alphecca',
    'Alpheratz',
    'Alpherg',
    'Alqiladah',
    'Alqubba',
    'Alrakis',
    'Alrescha',
    'Alruba',
    'Alrumh',
    'Alsafi',
    'Alsamaka',
    'Alsciaukat',
    'Alsephina',
    'Alshain',
    'Alshat',
    'Altair',
    'Altais',
    'Alterf',
    'Aludra',
    'Alula Australis',
    'Alula Borealis',
    'Alwasl',
    'Alya',
    'Alzirr',
    'Amadioha',
    'Amansinaya',
    'Anadolu',
    'Ancha',
    'Angetenar',
    'Aniara',
    'Ankaa',
    'Anser',
    'Antares',
    'Antinous',
    'Apamvatsa',
    'Apdu',
    'Arcalís',
    'Arcturus',
    'Arin-majlep',
    'Arkab Posterior',
    'Arkab Prior',
    'Arneb',
    'Ascella',
    'Asellus Australis',
    'Asellus Borealis',
    'Ashlesha',
    'Aspidiske',
    'Asterope',
    'Asuusiha',
    'Atakoraka',
    'Athebyne',
    'Atik',
    'Atlas',
    'Atria',
    'Aurwandilsta',
    'Avior',
    'Axólotl',
    'Ayeyarwady',
    'Azelfafage',
    'Azha',
    'Azmidi',
    'Añañuca',
    'Bade',
    'Baekdu',
    'Bagu',
    'Bajamar Star',
    'Bake-eo',
    'Baltesha',
    "Barnard's Star",
    'Baten Kaitos',
    'Batsũ̀',
    'Beehive Proplyd',
    'Beemim',
    'Beid',
    'Belel',
    'Bellatrix',
    'Berehynia',
    'Betelgeuse',
    'Bharani',
    'Bibhā',
    'Bibing',
    'Bie',
    'Biham',
    'Blaze Star',
    'Bodu',
    'Bosona',
    'Botein',
    'Brachium',
    'Bubup',
    'Buna',
    'Bunda',
    'Butterfly Star',
    'Bélénos',
    'Calvera',
    'Canopus',
    'Capella',
    'Caph',
    'Castor',
    'Castula',
    'Cebalrai',
    'Ceibo',
    'Celaeno',
    'Cervantes',
    'Cexing',
    'Chalawan',
    'Chamukuy',
    'Chaophraya',
    'Chara',
    'Chasoň',
    'Chechia',
    'Chertan',
    'Citadelle',
    'Citalá',
    'Cocibolca',
    'Copernicus',
    'Cor Caroli',
    'Cujam',
    'Cursa',
    'Custos',
    'Dabih',
    'Dajiangjunbei',
    'Dalim',
    'Danfeng',
    'Darlugal',
    'Deltoton',
    'Deneb',
    'Deneb Algedi',
    'Denebola',
    'Dhanishta',
    'Dhanuśarāgra',
    'Diadem',
    'Dilmun',
    'Dingolay',
    'Diphda',
    'Diya',
    'Dofida',
    'Dombay',
    'Dschubba',
    'Dubhe',
    'Dust-Ball',
    'Dziban',
    'Dìwö',
    'Ebla',
    'Edasich',
    'Electra',
    'Elgafar',
    'Elkurud',
    'Elnath',
    'Eltanin',
    'Emiw',
    'Enduri Senggu',
    'Enif',
    'Errai',
    'Fafnir',
    'Fang',
    'Fawaris',
    'Felis',
    'Felixvarela',
    'Filetdor',
    'Flegetonte',
    'Flying Saucer',
    'Fomalhaut',
    'Formosa',
    'Franz',
    'Frosty Leo',
    'Fulu',
    'Fumalsamakah',
    'Funi',
    'Furud',
    'Fuyue',
    'Gacrux',
    'Gaja',
    'Gakyid',
    'Gang',
    'Gar',
    'Garnet Star',
    'Geminga',
    'Genghe',
    'Giausar',
    'Gienah',
    'Ginan',
    'Gloas',
    'Gnomon',
    'Gomeisa',
    'Gouguo',
    'Grumium',
    'Guahayona',
    'Guansuo',
    'Gudja',
    'Gumala',
    'Guniibuu',
    'Guqi',
    'Hadar',
    'Haedus',
    'Hamal',
    'Hassaleh',
    'Hatysa',
    'Helvetios',
    'Heng',
    'Heryibwia',
    'Heze',
    'Hoerikwaggo',
    'Hoggar',
    'Holoea',
    'Homam',
    'Honores',
    'Horna',
    'Hru',
    'Huagai',
    'Hunahpú',
    'Hunor',
    'Hydor',
    'Iklil',
    'Illyrian',
    'Imai',
    'Inquill',
    'Intan',
    'Intercrus',
    'Irena',
    'Itonda',
    'Izar',
    'Jabbah',
    'Jian',
    'Jiantai',
    'Jishui',
    'Jiu',
    'Junnanmen',
    'Kaewkosin',
    'Kaffaljidhma',
    'Kaffalmusalsala',
    'Kalasungsang',
    'Kalausi',
    'Kamelos',
    'Kamuy',
    'Kang',
    'Karaka',
    'Kaus Australis',
    'Kaus Borealis',
    'Kaus Media',
    'Kautoki',
    'Kaveh',
    'Keid',
    'Kenemu',
    'Khambalia',
    'Khepdenreret',
    'Kitalpha',
    'Kochab',
    'Koeia',
    'Koit',
    'Komondor',
    'Kornephoros',
    'Kosjenka',
    'Kraz',
    'Krios',
    'Kronos',
    'Kui',
    'Kulou',
    'Kurhah',
    'La Superba',
    'Lang-Exster',
    'Larawag',
    'Leepwal',
    'Leidian',
    'Lembu',
    'Lerna',
    'Lesath',
    'Libertas',
    'Lich',
    'Liesma',
    'Ligong',
    'Lilii Borea',
    'Lionrock',
    'Lucilinburhuc',
    'Lumbung',
    'Lusitânia',
    'Maasym',
    'Macondo',
    'Maenalus',
    'Mago',
    'Magur',
    'Mahasim',
    'Mahsati',
    'Maia',
    'Malmok',
    'Marfik',
    'Markab',
    'Markeb',
    'Marsic',
    'Maru',
    'Matar',
    'Matrichakra',
    'Matza',
    'Mazaalai',
    'Mebsuta',
    'Megrez',
    'Meissa',
    'Mekbuda',
    'Meleph',
    'Menkalinan',
    'Menkar',
    'Menkent',
    'Menkib',
    'Merak',
    'Merga',
    'Meridiana',
    'Merope',
    'Mesarthim',
    'Miaplacidus',
    'Mimosa',
    'Minchir',
    'Minelauva',
    'Mintaka',
    'Mira',
    'Mirach',
    'Miram',
    'Mirfak',
    'Mirzam',
    'Misam',
    'Mizar',
    'Moldoveanu',
    'Montuno',
    'Morava',
    'Moriah',
    'Moth',
    'Mothallah',
    'Mouhoun',
    'Mpingo',
    'Muliphein',
    'Muning',
    'Muphrid',
    'Muscida',
    'Musica',
    'Muspelheim',
    'Márohu',
    'Mönch',
    'Naga',
    'Nahn',
    'Naledi',
    'Nandou',
    'Naos',
    'Nashira',
    'Natasha',
    'Necklace',
    'Neichu',
    'Nekkar',
    'Nembus',
    'Nenque',
    'Nervia',
    'Nganurganity',
    'Niandao',
    'Nihal',
    'Nikawiy',
    'Ninnisig',
    'Noquisi',
    'Nosaxa',
    'Nunki',
    'Nusakan',
    'Nushagak',
    'Nyamien',
    'Násti',
    'Nüchuang',
    'Ogma',
    'Okab',
    'Orkaria',
    'Pabilsang',
    'Pagru',
    'Paikauhale',
    'Paloma',
    'Paradys',
    'Parumleo',
    'Peacock',
    'Peony Star',
    'Petra',
    'Phact',
    'Phecda',
    'Pherkad',
    'Pherkad Minor',
    'Phoenicia',
    'Phyllon Kissinou',
    'Piautos',
    'Pincoya',
    'Ping',
    'Pipirima',
    'Pipit',
    'Pipoltr',
    'Pistol Star',
    'Pleione',
    'Poerava',
    'Polaris',
    'Polaris Australis',
    'Polis',
    'Pollux',
    'Pongaponga',
    'Porrima',
    'Praecipua',
    'Prima Hyadum',
    'Procyon',
    'Propus',
    'Protome',
    'Proxima Centauri',
    'Pulcherrima',
    'Qedty',
    'Qigong',
    'Quadrans',
    'Ramus',
    'Ran',
    'Rana',
    'Rangifer',
    'Rapeto',
    'Rasalas',
    'Rasalgethi',
    'Rasalhague',
    'Rasalnaqa',
    'Rastaban',
    'Red Rectangle',
    'Regulus',
    'Revati',
    'Rhombus',
    'Rigel',
    'Rigil Kentaurus',
    'Rosalíadecastro',
    'Rosette Eye',
    'Rotanev',
    'Ruchbah',
    'Rukbat',
    'Sabik',
    'Saclateni',
    'Sadachbia',
    'Sadalbari',
    'Sadalmelik',
    'Sadalsuud',
    'Sadr',
    'Safina',
    'Sagarmatha',
    'Saiph',
    'Salm',
    'Sansuna',
    'Sapaki',
    'Sargas',
    'Sarin',
    'Sarvvis',
    'Sceptrum',
    'Scheat',
    'Schedar',
    'Secunda Hyadum',
    'Segin',
    'Seginus',
    'Shakata',
    'Shakh',
    'Sham',
    'Shama',
    'Shangcheng',
    'Shangwei',
    'Shaomin',
    'Shaowei',
    'Sharjah',
    'Shatabhisha',
    'Shaula',
    'Sheliak',
    'Shengong',
    'Sheratan',
    'Shimu',
    'Sika',
    'Sirius',
    'Situla',
    'Siwarha',
    'Skat',
    'Solaris',
    'Solitaire',
    'Southern Crab',
    'Speedy Mic',
    'Spica',
    'Stella Ludoviciana',
    'Stellio',
    'Stephanos',
    'Sterrennacht',
    'Stribor',
    'Sualocin',
    'Subra',
    'Suhail',
    'Sukhurmashu',
    'Sulafat',
    'Syrma',
    'Sāmaya',
    'Tabit',
    'Taika',
    'Taiyangshou',
    'Taiyi',
    'Talitha',
    'Tangra',
    'Tania Australis',
    'Tania Borealis',
    'Tapecue',
    'Tarandus',
    'Tarazed',
    'Tarf',
    'Taygeta',
    'Tegmine',
    'Tejat',
    'Telum',
    'Tengshe',
    'Tepennekhet',
    'Tepiamenit',
    'Terebellum',
    'Tevel',
    'Theemin',
    'Thuban',
    'Tiaki',
    'Tianbang',
    'Tianbian',
    'Tianfu',
    'Tianguan',
    'Tianji',
    'Tianjinnan',
    'Tiansi',
    'Tianyi',
    'Tianyue',
    'Timir',
    'Tislit',
    'Titawin',
    'Tojil',
    'Toliman',
    'Tonatiuh',
    'Tonglingxing',
    'Torcular',
    'Triminus',
    'Tugongli',
    'Tuiren',
    'Tupi',
    'Tupã',
    'Tureis',
    'Tusizuo',
    'Udang',
    'Udkadua',
    'Ukdah',
    'Uklun',
    'Unukalhai',
    'Unurgunite',
    'Uridim',
    'Urquchillay',
    'Uruk',
    'Uñallamacha',
    'Uúba',
    'Vega',
    'Veritate',
    'Vindemiatrix',
    'Wasat',
    'Wattle',
    'Wazn',
    'Wezen',
    'Wouri',
    'Wurren',
    'Xami',
    'Xamidimura',
    'Xihe',
    'Xuange',
    'Yaqana',
    'Yed Posterior',
    'Yed Prior',
    'Yildun',
    'Yunü',
    'Yuyu',
    'Zaniah',
    'Zaurak',
    'Zavijava',
    'Zembra',
    'Zhang',
    'Zhou',
    'Zibal',
    'Zosma',
    'Zubenelgenubi',
    'Zubenelhakrabi',
    'Zubeneschamali',
    'Zuoqi',
    'Áldu',
)


def pick(rng: random.Random, count: int) -> list[str]:
    """``count`` distinct star names drawn from ``rng``.

    Deterministic given the RNG state, which is what keeps a seed reproducing a
    whole map — names included. If a map ever wants more systems than the
    catalogue has names (it cannot today: ``config.MAX_NODES`` is far smaller),
    the surplus is numbered rather than left blank.
    """
    if count <= len(NAMES):
        return rng.sample(NAMES, count)
    names = rng.sample(NAMES, len(NAMES))
    while len(names) < count:
        names.append(f"{NAMES[len(names) % len(NAMES)]} {len(names) // len(NAMES) + 1}")
    return names[:count]
